const MResource = {
  vi: {
    receiptPage: {
      process: "Quy trình",
      documents: "Thu, chi tiền",
      inspect: "Kiểm kê",
      inspectFund: "Kiểm kê quỹ",
      castFlow: "Dự báo dòng tiền",
      report: "Báo cáo",
      receiverMoney: "Thu tiền",
      pay: "Chi tiền",
      function: "Chức năng",
      show: "Xem",
      sum: "Tổng",
      majorMoney: "Nghiệp vụ tiền mặt",
      customer: "Khách hàng",
      provider: "Nhà cung cấp",
      employee: "Nhân viên",
      depositeRate: "Tính tỷ giá xuất quỹ",
      options: "Tùy chon",
      listMoneyDay: "Bảng kê số dư theo ngày",
      moneyFlow: "Dòng tiền",
      detailAccounting: "Số kế toán chi tiết quỹ tiền mặt",
      allReport: "Tất cả báo cáo",
      payment: "Phiếu chi",
      paymentForProvider: "1. Trả tiền nhà cung cấp (không theo hóa đơn)",
      guide: "Hướng dẫn",
      receiver: "Người nhận",
      address: "Địa chỉ",
      payReason: "Lý do chi tiền",
      attach: "Kèm theo",
      rootDocuments: "chứng từ gốc",
      dateAccounting: "Ngày hạch toán",
      datePayment: "Ngày phiếu chi",
      numPayment: "Số phiếu chi",
      accounting: "Hạch toán",
      typeMoney: "Loại tiền",
      description: "Diễn giải",
      money: "Số tiền",
      accountDebt: "Tài khoản nợ",
      accountBalance: "Tài khoản có",
      change: "Sửa",
      noted: "Ghi sổ",
      unNote: "Bỏ ghi",
      immediateChange: "Sửa nhanh",
      notEmptyDateAccounting: "Ngày hạch toán không được để trống",
      notEmptyDatePayment: "Ngày phiếu chi không được để trống",
      notEmptyPaymentCode: "Số phiếu chi không được để trống",
      needDetailDocument: "Bạn phải nhập chứng từ chi tiết",
      notEmptyAccountDebt: "Tài khoản nợ không được để trống",
      notEmptyAccountBalance: "Tài khoản có không được để trống",
      notFoundProviderCode: "Dữ liệu <Mã đối tượng> không có trong thư mục",
      notFoundEmployee: "Dữ liệu <Nhân viên> không có trong thư mục",
      notFoundAccountDebt: "Dữ liệu <Tk nợ> không có trong thư mục",
      notFoundAccountBalance: "Dữ liệu <Tk có> không có trong thư mục",
      needDateAccountingMoreThan: "Ngày hoặc toán phải lớn hơn hoặc bằng ngày chứng từ",
      noteSuccess: "Ghi sổ thành công.",
      numSuccess: "Số chứng từ thành công: ",
      numNotSuccess: "Số chứng từ chưa thành công: ",
      reason: "Nguyên nhân: Chứng từ đã ghi sổ không thể xóa",
      numDelete: "Chứng từ chưa bị xóa: ",
      payFor: "Chi tiền cho",
    },

    providerPage: {
      private: "Cá nhân",
      organization: "Tổ chức",
      isCustomer: "Là khách hàng",
      contactInfo: "Thông tin liên hệ",
      rulePayment: "Điều khoản thanh toán",
      bank: "Tài khoản ngân hàng",
      otherAddress: "Địa chỉ khác",
      note: "Ghi chú",
      contactPerson: "Người liên hệ",
      fullName: "Họ và tên",
      phone: "Số điện thoại",
      presentation: "Đại diện theo PL",
      contactSalutation: "Xưng hô",
      receiver: "Người nhận hóa đơn điện từ",
      mobilePhone: "Số điện thoại di động",
      phoneLandline: "Số điện thoại cố định",
      emails: `Email (Ngăn cách nhiêu email bởi dấu chấm phẩy ";")`,
      identify: "Thông tin CMND/Thẻ căn cước",
      identifyDate: "Ngày cấp",
      issuedBy: "Nơi cấp",
      debtDay: "Số ngày được nợ",
      maxDebt: "Số nợ tối đa",
      accountReceivers: "Tài khoản công nợ phải thu",
      accountDebt: "Tài khoản công nợ phải trả",
      bankNumber: "Số tài khoản",
      bankName: "Tên ngân hàng",
      branch: "Chi nhánh",
      city: "Tỉnh/TP của ngân hàng",
      addLine: "Thêm dòng",
      deleteAllLine: "Xóa hết dòng",
      location: "Vị trí địa lý",
      addressShip: "Địa chỉ giao hàng",
      sameAddressProvider: "Giống địa chỉ nhà cung cấp",

      fields: {
        ProviderCode: "Mã nhà cung cấp",
        ProviderTaxCode: "Mã số thuế",
        ProviderName: "Tên nhà cung cấp",
        ProvidePhone: "Điện thoại",
        ProviderWebsite: "Website",
        ListGroupId: "Nhóm nhà cung cấp",
        EmployeeId: "Nhân viên mua hàng",
        ProviderAddress: "Địa chỉ",
      },
      notEmtpyProviderCode: "Mã nhà cung cấp không được để trống",
      notEmptyProviderName: "Tên nhà cung cấp không được để trống",
      notDuplicateBankNumber: "Số tài khoản không được phép trùng, vui lòng kiểm tra lại",
      ruleNotFound: "Dữ liệu <Điều khoản thanh toán> không có trong danh mục",
      employeeNotFound: "Dữ liệu <Nhân viên mua hàng> không có trong danh mục",
      accountDebtNotFound: "Dữ liệu <Tài khoản công nợ phải trả> không có trong danh mục",
      accountBalanceNotFound: "Dữ liệu <Tài khoản công nợ phải thu> không có trong danh mục",
      deleteQuestion: "Bạn chắc chắn muốn xóa những bản ghi đã chọn?",
      country: "Quốc gia",
      cityCombobox: "Tình/Thành phố",
      district: "Quận/huyện",
      wards: "Xã/phường",
    },

    accountPage: {
      accountDetail: {
        detailInspect: "Theo dõi chi tiết theo",
        object: "Đối tượng",
        objectTHCP: "Đối tượng THCP",
        order: "Đơn đặt hàng",
        purchaseContract: "Hợp đồng mua",
        department: "Đơn vị",
        bank: "Tài khoản ngân hàng",
        construction: "Công trình",
        paymentContract: "Hợp đồng bán",
        itemCP: "khoản mục CP",
        code: "Mã thống kê",
        provider: "Nhà cung cấp",
        addSuccess: "Thêm bản ghi thành công",
        changeSuccess: "Sửa bản ghi thành công",
        notChooseSelf: "Không thể chọn tài khoản tổng hợp là chính nó.",
        invalidAccountCodeAndParent: "Số tài khoản có độ dài > 3 kí tự phải điền thông tin <Tài khoản tổng hợp>",
        invalidLengthAccountCode: "Số tài khoản phải có độ dài >= 3 ký tự",
        inValidFormatAccountCode: "Số tài khoản chi tiết phải bắt đầu bằng số tài khoản tổng hợp",
        invalidLengthAccountAndParent: "Độ dài số tài khoản chỉ được lớn hơn độ dài <Tài khoản tổng hợp> 1 kí tự",
      },
      accountList: {
        updateAllQuestion: `
Bạn có muốn thiết lập trạng thái "Sử dụng" cho tất cả <Tài khoản> con không?`,
        accountCode: "Số tài khoản",
        accountName: "Tên tài khoản",
        englishName: "Tên tiếng anh",
        parentAccount: "Tài khoản tổng hợp",
        nature: "Tính chất",
        description: "Diễn giải",
        exceptionAccountant: "Có hách toán ngoại lệ",
        allApps: "Tất cả danh mục",
        expand: "Mở rộng",
        collapse: "Thu gọn",
        importExcel: "Nhập từ Excel",
        deleteSuccess: "Xóa thành công!",
        stop: "Ngừng sử dụng",
        use: "Sử dụng",
      },
    },

    listAccountNature: [
      {
        AccountNatureId: 0,
        AccountNatureName: "Dư nợ",
      },
      {
        AccountNatureId: 1,
        AccountNatureName: "Dư có",
      },
      {
        AccountNatureId: 2,
        AccountNatureName: "Lưỡng tính",
      },
      {
        AccountNatureId: 3,
        AccountNatureName: "Không có số dư",
      },
    ],

    listAccountObject: [
      {
        AccountObjectId: 0,
        AccountObjectName: "Nhà cung cấp",
      },
      {
        AccountObjectId: 1,
        AccountObjectName: "Khách hàng",
      },
      {
        AccountObjectId: 2,
        AccountObjectName: "Nhân viên",
      },
    ],

    companyName: {
      misa: "CÔNG TY CỔ PHẦN MISA",
    },
    detailForm: {
      name: "Thông tin nhân viên",
      successMsg: "Sửa bản ghi thành công!",
      failMsg: "Sửa bản ghi thất bại",
      placeholderDepartment: "--Chọn đơn vị--",
    },
    newForm: {
      name: "Thêm mới nhân viên",
      successMsg: "Thêm mới bản ghi thành công!",
      failMsg: "Thêm mới bản ghi thất bại",
    },

    detailAccountForm: {
      name: "Sửa tài khoản",
      successMsg: "Sửa bản ghi thành công!",
      failMsg: "Sửa bản ghi thất bại",
    },

    addAccountForm: {
      name: "Thêm tài khoản",
      successMsg: "Thêm mới bản ghi thành công!",
      failMsg: "Thêm mới bản ghi thất bại",
    },
    account: {
      status: {
        0: "Ngừng sử dụng",
        1: "Sử dụng",
      },
    },

    table: {
      noData: "Không có dữ liệu",
      title: "Nhân viên",
      functionHeader: "CHỨC NĂNG",
      total: "Tổng số",
      record: "bản ghi",
      app: "Danh mục",
      account: "Hệ thống tài khoản",
      provider: "Danh sách nhà cung cấp",
      header: [
        {
          id: 0,
          headerName: "MÃ NHÂN VIÊN",
          className: ["width-150"],
          fieldName: "EmployeeCode",
        },
        {
          id: 1,
          headerName: "TÊN NHÂN VIÊN",
          className: ["width-200"],
          fieldName: "FullName",
        },
        {
          id: 2,

          headerName: "GIỚI TÍNH",
          className: ["width-100"],
          fieldName: "Gender",
          type: "gender",
        },
        {
          id: 3,

          headerName: "NGÀY SINH",
          className: ["width-150", "text-align-center"],
          fieldName: "DateOfBirth",
          type: "date",
        },
        {
          id: 4,
          headerName: "SỐ CMND",
          className: ["width-200"],
          fieldName: "IdentityNumber",
          title: "Số chứng minh thư nhân dân",
        },
        {
          id: 5,
          headerName: "CHỨC DANH",
          className: ["width-150"],
          fieldName: "PositionName",
        },
        {
          id: 6,
          headerName: "TÊN ĐƠN VỊ",
          className: ["width-200"],
          fieldName: "DepartmentName",
        },
        {
          id: 7,
          headerName: "SỐ TÀI KHOẢN",
          className: ["width-200"],
          fieldName: "BankAccount",
        },
        {
          id: 8,
          headerName: "TÊN NGÂN HÀNG",
          className: ["width-200"],
          fieldName: "BankName",
        },
        {
          id: 9,
          headerName: "CHI NHÁNH TK NGÂN HÀNG",
          className: ["width-250"],
          fieldName: "BankBranch",
          title: "CHI NHÁNH TÀI KHOẢN NGÂN HÀNG",
        },
      ],
      headerProvider: [
        {
          id: 0,
          headerName: "Mã nhà cung cấp",
          className: ["width-150"],
          fieldName: "ProviderCode",
        },
        {
          id: 1,
          headerName: "Tên nhà cung cấp",
          className: ["width-200"],
          fieldName: "ProviderName",
        },
        {
          id: 2,
          headerName: "Địa chỉ",
          className: ["width-250"],
          fieldName: "ProvideAddress",
        },
        {
          id: 3,
          headerName: "Mã số thuế",
          className: ["width-200"],
          fieldName: "ProviderTaxCode",
        },
        {
          id: 4,
          headerName: "Điện thoại",
          className: ["width-200"],
          fieldName: "ProvidePhone",
        },
        {
          id: 5,
          headerName: "Người liên hệ",
          className: ["width-200"],
          fieldName: "ContactPerson",
        },
        {
          id: 6,
          headerName: "Người đại diện PL",
          className: ["width-200"],
          fieldName: "RepresentPerson",
        },
        {
          id: 7,
          headerName: "Tổ chức/Cá nhân",
          className: ["width-200"],
          fieldName: "ProviderIsPrivate",
        },
      ],
      headerAccountTable: [
        {
          id: 0,
          headerName: "Số tài khoản",
          className: ["width-200"],
          fieldName: "AccountCode",
        },
        {
          id: 1,
          headerName: "Tên Tài khoản",
          className: ["width-250"],
          fieldName: "AccountName",
        },
        {
          id: 2,
          headerName: "Tính chất",
          className: ["width-150"],
          fieldName: "AccountNature",
        },
        {
          id: 3,
          headerName: "Tên tiếng anh",
          className: ["width-250"],
          fieldName: "AccountEnglishName",
        },
        {
          id: 4,
          headerName: "Diễn giải",
          className: ["width-250"],
          fieldName: "AccountDescription",
        },
        {
          id: 5,
          headerName: "Trạng thái",
          className: ["width-150"],
          fieldName: "AccountStatus",
        },
      ],
      recordsPerPage: [
        {
          value: 10,
          text: "10 bản ghi trên một trang",
        },
        {
          value: 20,
          text: "20 bản ghi trên một trang",
        },
        {
          value: 30,
          text: "30 bản ghi trên một trang",
        },
        {
          value: 40,
          text: "40 bản ghi trên một trang",
        },
        {
          value: 50,
          text: "50 bản ghi trên một trang",
        },
      ],
    },

    fieldsAccountForm: {
      AccountCode: "Số tài khoản",
      AccountName: "Tên tài khoản",
      AccountNature: "Tính chất",
    },

    button: {
      addEmployee: "Thêm",
      doMultiple: "Thực hiện hàng loạt",
      saveAndNew: "Cất và Thêm",
      save: "Cất",
      cancel: "Hủy",
      accept: "Đồng ý",
      refuse: "Không",
      duplicate: "Nhân bản",
      delete: "Xóa",
      stopUse: "Ngừng sử dụng",
      use: "Sử dụng",
      utility: "Tiện ích",
      convertAccount: "Chuyển tài khoản hạch toán",
      note: "Ghi sổ",
      unNote: "Bỏ ghi",
    },

    dialog: {
      delete: "Xóa",
      success: "thành công",
      confirmDeleteMsg: "Bạn chắc chắn muốn xóa",
      title: "Dữ liệu không hợp lệ",
      titleDelete: "Kết quả xóa chứng từ",
      titleQuestionSave: "Cất bản ghi?",
      titleQuestionDelete: "Xóa bản ghi?",
      titleFailSystem: "Lỗi máy chủ",
      descQuestionSave: "Dữ liệu đã thay đổi. Bạn có muốn cất không?",
      descQuestionDelete: "Bạn chắc chắn muốn xóa nhân viên ",
      statusSuccess: "Thành công! ",
      successDeleteToastMsg: "Xóa bản ghi thành công!",
      statusFail: "Thất bại! ",
      failDeleteToastMsg: "Xóa bản ghi thất bại!",
      failSystemMsg: "Máy chủ đang xảy ra sự cố, vui lòng quay lại sau.",
    },

    shortcut: {
      save: "Cất (Ctrl + S)",
      saveAndNew: "Cất và thêm(Ctrl + Shift + S)",
    },

    placeholder: {
      searchByCodeAndName: "Tìm kiếm theo mã, tên nhân viên",
      searchByKey: "Nhập từ khóa tìm kiếm",
    },

    titleIcon: {
      refresh: "Tải lại",
      help: "Giúp",
      close: "Đóng (ESC)",
      excel: "Xuất ra Excel",
    },

    gender: {
      male: "Nam",
      female: "Nữ",
      other: "Khác",
    },
    fields: {
      EmployeeCode: "Mã",
      FullName: "Tên",
      DateOfBirth: "Ngày sinh",
      DepartmentId: "Đơn vị",
      Gender: "Giới tính",
      PositionName: "Chức danh",
      IdentityNumber: "Số CMND",
      IdentityAddress: "Nơi cấp",
      IdentityDate: "Ngày cấp",
      Address: "Địa chỉ",
      PhoneNumber: "ĐT di động",
      PhoneLandline: "ĐT cố định",
      BankAccount: "Tài khoản ngân hàng",
      BankName: "Tên ngân hàng",
      BankBranch: "Chi nhánh",
      Email: "Email",
      isProvider: "Là nhà cung cấp",
      isCustomer: "Là Khách hàng",
      title: {
        identity: "Số chứng minh thư nhân dân",
        phoneNumber: "Điện thoại di động",
        phoneLandline: "Điện thoại cố định",
      },
    },
    warning: {
      invalidDepartment: "Đơn vị không tồn tại",
      noGreaterThan: "không được lớn hơn",
      noEmpty: "không được để trống",
      char: "kí tự",
      notFound: "Không tìm thấy",
      invalidDateOfBirth: "Ngày sinh không được lớn hơn ngày hiện tại",
      invalidIdentityDate: "Ngày cấp không được lớn hơn ngày hiện tại",
      invalidEmail: "Email không hợp lệ",
      invalidCode: "Mã nhân viên đã tồn tại",
    },

    fileName: {
      employeeExcel: "Danh_sach_nhan_vien.xlsx",
      accountExcle: "Danh_sach_he_thong_tai_khoan.xlsx",
      providerExcel: "Danh_sach_nha_cung_cap.xlsx",
      receiptExcel: "Danh_sach_phieu_thu.xlsx",
    },

    maxLength: {
      code: 20,
      name: 100,
      phoneNumber: 50,
      bankNumber: 25,
      address: 255,
    },
  },
};

export default MResource;
